//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class DB日統計資訊
    {
        public string 年月日 { get; set; }
        public int 註冊數 { get; set; }
        public int Molo註冊數 { get; set; }
        public int 總人數 { get; set; }
        public int 登入數 { get; set; }
        public int 簽到數 { get; set; }
        public int FB推廣總數 { get; set; }
        public int 文章發文總數 { get; set; }
        public int 文章回覆總數 { get; set; }
        public int 文章推文總數 { get; set; }
        public int 文章留言總數 { get; set; }
        public int 文章瀏覽總數 { get; set; }
        public int 新聞回覆總數 { get; set; }
        public int 專欄回覆總數 { get; set; }
        public int 會員持有鐵幣 { get; set; }
        public int 贈送總鐵幣 { get; set; }
        public int 收回總鐵幣 { get; set; }
        public Nullable<System.DateTime> 建立日期 { get; set; }
    }
}
