//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class DB錯誤記錄
    {
        public int 錯誤號碼 { get; set; }
        public int 錯誤嚴重性 { get; set; }
        public int 錯誤狀態碼 { get; set; }
        public string 觸發程序名稱 { get; set; }
        public string 錯誤訊息 { get; set; }
        public int 錯誤行號 { get; set; }
        public System.DateTime 建立日期 { get; set; }
    }
}
