//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [Serializable]
    public partial class IronEntities : DbContext
    {
        public IronEntities()
            : base("name=IronEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DB日統計資訊> DB日統計資訊 { get; set; }
        public DbSet<DB錯誤記錄> DB錯誤記錄 { get; set; }
        public DbSet<RP檔> RP檔 { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<人員識別> 人員識別 { get; set; }
        public DbSet<公告> 公告 { get; set; }
        public DbSet<文章> 文章 { get; set; }
        public DbSet<文章回覆> 文章回覆 { get; set; }
        public DbSet<文章回覆檔案> 文章回覆檔案 { get; set; }
        public DbSet<文章留言> 文章留言 { get; set; }
        public DbSet<文章動作記錄> 文章動作記錄 { get; set; }
        public DbSet<文章檔案> 文章檔案 { get; set; }
        public DbSet<文章屬性> 文章屬性 { get; set; }
        public DbSet<好友> 好友 { get; set; }
        public DbSet<行事曆> 行事曆 { get; set; }
        public DbSet<即時訊息> 即時訊息 { get; set; }
        public DbSet<系統使用者> 系統使用者 { get; set; }
        public DbSet<系統使用者異動歷程> 系統使用者異動歷程 { get; set; }
        public DbSet<直播列表> 直播列表 { get; set; }
        public DbSet<活動_連續登入加碼送> 活動_連續登入加碼送 { get; set; }
        public DbSet<相片> 相片 { get; set; }
        public DbSet<相簿> 相簿 { get; set; }
        public DbSet<英雄列表> 英雄列表 { get; set; }
        public DbSet<英雄攻略> 英雄攻略 { get; set; }
        public DbSet<英雄攻略_會員推文> 英雄攻略_會員推文 { get; set; }
        public DbSet<英雄攻略回覆> 英雄攻略回覆 { get; set; }
        public DbSet<訊息通知> 訊息通知 { get; set; }
        public DbSet<國家> 國家 { get; set; }
        public DbSet<專欄> 專欄 { get; set; }
        public DbSet<專欄回覆> 專欄回覆 { get; set; }
        public DbSet<專欄動作記錄> 專欄動作記錄 { get; set; }
        public DbSet<專欄牆> 專欄牆 { get; set; }
        public DbSet<登出入歷程> 登出入歷程 { get; set; }
        public DbSet<意見反應> 意見反應 { get; set; }
        public DbSet<意見反應屬性> 意見反應屬性 { get; set; }
        public DbSet<新聞> 新聞 { get; set; }
        public DbSet<新聞回覆> 新聞回覆 { get; set; }
        public DbSet<新聞動作記錄> 新聞動作記錄 { get; set; }
        public DbSet<新聞點擊> 新聞點擊 { get; set; }
        public DbSet<新聞屬性> 新聞屬性 { get; set; }
        public DbSet<會員> 會員 { get; set; }
        public DbSet<會員文章收藏> 會員文章收藏 { get; set; }
        public DbSet<會員文章訂閱> 會員文章訂閱 { get; set; }
        public DbSet<會員交易> 會員交易 { get; set; }
        public DbSet<會員回覆推文> 會員回覆推文 { get; set; }
        public DbSet<會員訂閱> 會員訂閱 { get; set; }
        public DbSet<會員計數> 會員計數 { get; set; }
        public DbSet<會員停權鎖定> 會員停權鎖定 { get; set; }
        public DbSet<會員停權鎖定歷程> 會員停權鎖定歷程 { get; set; }
        public DbSet<會員專欄收藏> 會員專欄收藏 { get; set; }
        public DbSet<會員推文> 會員推文 { get; set; }
        public DbSet<會員異動歷程> 會員異動歷程 { get; set; }
        public DbSet<會員新聞收藏> 會員新聞收藏 { get; set; }
        public DbSet<會員簽到> 會員簽到 { get; set; }
        public DbSet<業餘戰隊> 業餘戰隊 { get; set; }
        public DbSet<業餘戰隊_文章> 業餘戰隊_文章 { get; set; }
        public DbSet<業餘戰隊_文章回覆> 業餘戰隊_文章回覆 { get; set; }
        public DbSet<業餘戰隊_文章留言> 業餘戰隊_文章留言 { get; set; }
        public DbSet<業餘戰隊_文章屬性> 業餘戰隊_文章屬性 { get; set; }
        public DbSet<業餘戰隊_推文> 業餘戰隊_推文 { get; set; }
        public DbSet<業餘戰隊加入區> 業餘戰隊加入區 { get; set; }
        public DbSet<業餘戰隊申請區> 業餘戰隊申請區 { get; set; }
        public DbSet<業餘戰隊回覆推文> 業餘戰隊回覆推文 { get; set; }
        public DbSet<業餘戰隊成員> 業餘戰隊成員 { get; set; }
        public DbSet<業餘戰隊約戰> 業餘戰隊約戰 { get; set; }
        public DbSet<電競選手> 電競選手 { get; set; }
        public DbSet<電競選手照片> 電競選手照片 { get; set; }
        public DbSet<稱號設定> 稱號設定 { get; set; }
        public DbSet<影片> 影片 { get; set; }
        public DbSet<影片回覆> 影片回覆 { get; set; }
        public DbSet<暱稱列表> 暱稱列表 { get; set; }
        public DbSet<論壇列表> 論壇列表 { get; set; }
        public DbSet<趣味遊戲_下注> 趣味遊戲_下注 { get; set; }
        public DbSet<趣味遊戲_主客> 趣味遊戲_主客 { get; set; }
        public DbSet<趣味遊戲_主檔> 趣味遊戲_主檔 { get; set; }
        public DbSet<趣味遊戲_明細> 趣味遊戲_明細 { get; set; }
        public DbSet<趣味遊戲_開盤> 趣味遊戲_開盤 { get; set; }
        public DbSet<趣味遊戲_對戰表> 趣味遊戲_對戰表 { get; set; }
        public DbSet<趣味遊戲主客編號> 趣味遊戲主客編號 { get; set; }
        public DbSet<趣味遊戲項目> 趣味遊戲項目 { get; set; }
        public DbSet<趣味遊戲編號> 趣味遊戲編號 { get; set; }
        public DbSet<導覽圖片> 導覽圖片 { get; set; }
        public DbSet<導覽廣告> 導覽廣告 { get; set; }
        public DbSet<導覽影片> 導覽影片 { get; set; }
        public DbSet<戰隊> 戰隊 { get; set; }
        public DbSet<戰隊成員> 戰隊成員 { get; set; }
        public DbSet<擅用英雄> 擅用英雄 { get; set; }
        public DbSet<賽事> 賽事 { get; set; }
        public DbSet<賽事隊伍> 賽事隊伍 { get; set; }
        public DbSet<賽事隊員> 賽事隊員 { get; set; }
        public DbSet<爐石卡片> 爐石卡片 { get; set; }
        public DbSet<爐石攻略> 爐石攻略 { get; set; }
        public DbSet<爐石攻略回覆> 爐石攻略回覆 { get; set; }
        public DbSet<爐石套牌> 爐石套牌 { get; set; }
        public DbSet<爐石素質> 爐石素質 { get; set; }
        public DbSet<爐石職業> 爐石職業 { get; set; }
        public DbSet<鐵幣異動記錄> 鐵幣異動記錄 { get; set; }
    }
}
