//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class RP檔
    {
        public long RP流水號 { get; set; }
        public string 種族A { get; set; }
        public string 選手A { get; set; }
        public string 選手A圖片 { get; set; }
        public string 種族B { get; set; }
        public string 選手B { get; set; }
        public string 選手B圖片 { get; set; }
        public string 賽事 { get; set; }
        public string 檔案路徑 { get; set; }
        public int 下載次數 { get; set; }
        public System.DateTime 上傳時間 { get; set; }
        public string 異動者 { get; set; }
        public int 論壇識別 { get; set; }
    }
}
