//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 即時訊息
    {
        public long 流水號 { get; set; }
        public string 訊息發送者 { get; set; }
        public string Icon名稱1 { get; set; }
        public string 訊息接收者 { get; set; }
        public string Icon名稱2 { get; set; }
        public string 訊息內容 { get; set; }
        public bool 讀取YN { get; set; }
        public System.DateTime 建立日期 { get; set; }

        public 即時訊息() { }
        public 即時訊息(DataRow dr)
        {
            流水號 = long.Parse(dr["流水號"].ToString());
            訊息發送者 = dr["訊息發送者"].ToString();
            Icon名稱1 = dr["Icon名稱1"].ToString();
            if (Icon名稱1.IndexOf("http") == -1)
            {
                if (Icon名稱1 == "")
                    Icon名稱1 = "http://w2.ironforum.com.tw/icon/default.png";      
                else
                    Icon名稱1 = myStatic.toClientUrl("~/img/icon/" + Icon名稱1);            
            }
            訊息接收者 = dr["訊息接收者"].ToString();
            Icon名稱2 = dr["Icon名稱2"].ToString();
            if (Icon名稱2.IndexOf("http") == -1)
            {
                if (Icon名稱2 == "")
                    Icon名稱2 = "http://w2.ironforum.com.tw/icon/default.png";   
                else
                    Icon名稱2 = myStatic.toClientUrl("~/img/icon/" + Icon名稱2);
            }
            訊息內容 = dr["訊息內容"].ToString();
            讀取YN = bool.Parse(dr["讀取YN"].ToString());
            建立日期 = DateTime.Parse(dr["建立日期"].ToString());
        }
    }
}
