//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品
    {
        public long 商品流水號 { get; set; }
        public int 廠商編號 { get; set; }
        public string 商品名稱 { get; set; }
        public int 售價 { get; set; }
        public int 特價 { get; set; }
        public int 鉄幣價格 { get; set; }
        public string 一般圖片 { get; set; }
        public string 滑過圖片 { get; set; }
        public int 商品狀態 { get; set; }
        public bool 上架YN { get; set; }
        public bool 熱門YN { get; set; }
        public string 商品材質 { get; set; }
        public string 商品描述 { get; set; }
        public string 尺寸表 { get; set; }
        public string 關鍵字 { get; set; }
        public Nullable<System.DateTime> 特價開始日 { get; set; }
        public Nullable<System.DateTime> 特價結束日 { get; set; }
        public string 異動者 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public int 商品類別 { get; set; }
    }
}
