//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 好友
    {
        M_Member MH = new M_Member();

        public string 名稱1 { get; set; }
        public string Icon名稱1 { get; set; }
        public string 問候訊息 { get; set; }
        public string 名稱2 { get; set; }
        public string Icon名稱2 { get; set; }
        public bool 確認2 { get; set; }
        public Nullable<System.DateTime> 確認日 { get; set; }
        public byte 好友狀態 { get; set; }
        public DateTime 建立日期 { get; set; }

        public string icon = "";
        public string link = "";
        public string nickname = "";

        public Userinfo whoami;
        public Userinfo friendinfo;

        public 好友() { }
        public 好友(DataRow dr, Userinfo whoami)
        { 
            名稱1 = dr["名稱1"].ToString();
            Icon名稱1 = dr["Icon名稱1"].ToString();
            問候訊息 = dr["問候訊息"].ToString();
            名稱2 = dr["名稱2"].ToString();
            Icon名稱2 = dr["Icon名稱2"].ToString();
            確認2 = bool.Parse(dr["確認2"].ToString());
            if(dr["確認日"].ToString()!="")
             確認日 = DateTime.Parse(dr["確認日"].ToString());
            建立日期 = DateTime.Parse(dr["建立日期"].ToString());
            好友狀態 = byte.Parse(dr["好友狀態"].ToString());

            this.whoami = whoami;
        }
        public void bindprofile()
        {
            if (名稱1 == whoami.Nickname)
                friendinfo = MH.getProfileByNickname(名稱2);
            else
                friendinfo = MH.getProfileByNickname(名稱1);
        }
        public string iconDisplay
        {
            get
            {
                string icon;
                if (名稱1 == whoami.Nickname)
                    icon = Icon名稱2;
                else
                    icon = Icon名稱1;

                if (icon == "")
                    icon = myStatic.toHttpUrl("~/image/content/default.png");
                else if (icon.IndexOf("http") == -1)
                    icon = "http://w3.ironforum.com.tw/icon/" + icon;

                return icon;
            }
        }

        public string Nickname
        {
            get
            {
                if (名稱1 == whoami.Nickname)
                    return 名稱2;
                else
                    return 名稱1;
            }
        }
        public string friendlink
        {
            get
            {
                return friendinfo.IconLink;
            }
        }
    }
}
