//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 影片
    {
        public long 影片流水號 { get; set; }
        public string 標題 { get; set; }
        public string 內容 { get; set; }
        public int 影片狀態 { get; set; }
        public bool 置首YN { get; set; }
        public bool 推薦YN { get; set; }
        public string 圖片路徑 { get; set; }
        public string 影片連結 { get; set; }
        public System.DateTime 發佈開始日 { get; set; }
        public Nullable<System.DateTime> 發佈結束日 { get; set; }
        public string 異動者 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public int 論壇識別 { get; set; }
        public int 影片識別 { get; set; }
        public long 點擊數 { get; set; }
    }
}
