//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 戰隊
    {
        public int 論壇識別 { get; set; }
        public int 戰隊編號 { get; set; }
        public string 戰隊Logo { get; set; }
        public string 戰隊隊名 { get; set; }
        public string 戰隊圖片 { get; set; }
        public string 母企業 { get; set; }
        public string 贊助企業 { get; set; }
        public string 戰隊介紹 { get; set; }
        public string 歷年戰績 { get; set; }
        public string 國名 { get; set; }
        public int 成員數 { get; set; }
        public DateTime 成立時間;
        public string 備註 { get; set; }
        //隊員的表
        public DataTable DTfighters;
        public List<sponserObj> sponserlist;

        public 戰隊() { }
        public 戰隊(DataRow dr)
	    {
            論壇識別 = int.Parse(dr["論壇識別"].ToString());
            戰隊編號 = int.Parse(dr["戰隊編號"].ToString());
            戰隊Logo = dr["戰隊Logo"].ToString();
            戰隊隊名 = dr["戰隊隊名"].ToString();
            戰隊圖片 = dr["戰隊圖片"].ToString();
            母企業 = dr["母企業"].ToString();
            贊助企業 = dr["贊助企業"].ToString();
            戰隊介紹 = dr["戰隊介紹"].ToString();
            歷年戰績 = dr["歷年戰績"].ToString();
            國名 = dr["國名"].ToString();
            成員數 = int.Parse(dr["成員數"].ToString());
            DateTime.TryParse(dr["成立時間"].ToString(), out 成立時間);

            string[] ary = 贊助企業.Split(',');
            sponserlist = new List<sponserObj>();

            for (int i = 0; i < ary.Length; i += 2)
            {
                if (i+1 >= ary.Length)
                    break;
                sponserlist.Add(new sponserObj(ary[i], ary[i + 1]));
            }
	        }

            //綁定隊員
            public void BindFighters()
            {
                M_Team MT = new M_Team();
                DTfighters = new DataTable();
                DataSet ds = MT.DSteamMember(0, 0, 戰隊編號);
                DTfighters = ds.Tables[0];
                成員數 = ds.Tables[0].Rows.Count;
            }
        }

    public class sponserObj
    {
        public string name;
        public string icon;
        public sponserObj(string icon, string name)
        {
            this.name = name;
            this.icon = icon;
        }
    }
}
