//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 攻略留言
    {
        public long 攻略流水號 { get; set; }
        public long 回覆流水號 { get; set; }
        public long 留言流水號 { get; set; }
        public string MoloKey { get; set; }
        public string 暱稱 { get; set; }
        public string 內容 { get; set; }
        public int 留言狀態 { get; set; }
        public bool 置頂YN { get; set; }
        public System.DateTime 置頂時間 { get; set; }
        public bool 隱藏YN { get; set; }
        public bool 水桶YN { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public int 攻略識別 { get; set; }
    }
}
