//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 文章屬性
    {
        public int 屬性編號 { get; set; }
        public string 屬性名稱 { get; set; }
        public string 屬性圖片 { get; set; }
        public int 屬性狀態 { get; set; }
        public string 備註 { get; set; }
        public bool 隱藏YN { get; set; }
        public string 版主 { get; set; }
        public string 副版主 { get; set; }
        public System.DateTime 置頂時間 { get; set; }
        public System.DateTime 建立時間 { get; set; }
        public int 論壇識別 { get; set; }

        public 文章屬性(){}
        public 文章屬性(DataRow dr)
        {
            屬性編號 = int.Parse(dr["屬性編號"].ToString());
            屬性名稱 = dr["屬性名稱"].ToString();
            屬性圖片 = dr["屬性圖片"].ToString();
            屬性狀態 = int.Parse(dr["屬性狀態"].ToString());
            備註 = dr["備註"].ToString();
            隱藏YN = bool.Parse(dr["隱藏YN"].ToString()); 
            版主 = dr["版主"].ToString();
            副版主 = dr["副版主"].ToString();
            置頂時間 = DateTime.Parse(dr["置頂時間"].ToString());
            建立時間 = DateTime.Parse(dr["建立時間"].ToString());
            論壇識別 = int.Parse(dr["論壇識別"].ToString());
        }
    }
}
