//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 文章
    {
        public int 屬性編號 { get; set; }
        public string MoloKey { get; set; }
        public long 文章流水號 { get; set; }
        public string 標題 { get; set; }
        public string 內容 { get; set; }
        public int 文章狀態 { get; set; }
        public bool 置頂YN { get; set; }
        public System.DateTime 置頂時間 { get; set; }
        public bool 推薦YN { get; set; }
        public bool 前台推薦YN { get; set; }
        public bool 精華YN { get; set; }
        public bool 隱藏YN { get; set; }
        public bool 鎖定YN { get; set; }
        public bool 水桶YN { get; set; }
        public string 圖片路徑 { get; set; }
        public string 影片連結 { get; set; }
        public int 推文數 { get; set; }
        public int 回覆數 { get; set; }
        public int 人氣數 { get; set; }
        public string 異動者 { get; set; }
        public System.DateTime 發佈開始日 { get; set; }
        public DateTime 最後回覆日;
        public System.DateTime 建立日期 { get; set; }
        public bool 前台刪除YN { get; set; }
        public int 論壇識別 { get; set; }

        public string 屬性名稱 = "";
        public string 暱稱 = "";
        public string 屬性圖片 = "";

        public 文章(){}
        public 文章(DataRow dr)
        {
            屬性編號 = int.Parse(dr["屬性編號"].ToString());
            屬性名稱 = dr["屬性名稱"].ToString();
            MoloKey = dr["MoloKey"].ToString();
            文章流水號 = long.Parse(dr["文章流水號"].ToString());
            標題 = dr["標題"].ToString();
            內容 = dr["內容"].ToString();
            異動者 = dr["異動者"].ToString();
            文章狀態 = int.Parse(dr["文章狀態"].ToString());
            置頂YN = bool.Parse(dr["置頂YN"].ToString());
            推薦YN = bool.Parse(dr["推薦YN"].ToString()); 
            前台推薦YN = bool.Parse(dr["前台推薦YN"].ToString());
            精華YN = bool.Parse(dr["精華YN"].ToString());
            隱藏YN = bool.Parse(dr["隱藏YN"].ToString());
            鎖定YN = bool.Parse(dr["鎖定YN"].ToString());
            水桶YN = bool.Parse(dr["水桶YN"].ToString());
            圖片路徑 = dr["圖片路徑"].ToString();
            影片連結 = dr["影片連結"].ToString();
            推文數 = int.Parse(dr["推文數"].ToString());
            回覆數 = int.Parse(dr["回覆數"].ToString());
            人氣數 = int.Parse(dr["人氣數"].ToString());
            前台刪除YN = bool.Parse(dr["前台刪除YN"].ToString());
            論壇識別 = int.Parse(dr["論壇識別"].ToString());
            建立日期 = DateTime.Parse(dr["建立日期"].ToString());
            發佈開始日 = DateTime.Parse(dr["發佈開始日"].ToString());
            DateTime.TryParse(dr["最後回覆日"].ToString(), out 最後回覆日);
            置頂時間 = DateTime.Parse(dr["置頂時間"].ToString());
            暱稱 = dr["暱稱"].ToString();
            屬性圖片 = dr["屬性圖片"].ToString();

        }

        public string link
        {
            get
            {
                if(myStatic.online)
                    return myStatic.toClientUrl(url.forumdetail) + "/" + 屬性編號 + "/" + 文章流水號 + "/1/" + 論壇識別;
                else
                    return myStatic.webPath + myStatic.toClientUrl(url.forumdetail) + "/" + 屬性編號 + "/" + 文章流水號 + "/1/" + 論壇識別;
            }
        }
        
    }
    
}
