//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 文章回覆
    {
        public long 文章流水號 { get; set; }
        public long 回覆流水號 { get; set; }
        public string MoloKey { get; set; }
        public string 內容 { get; set; }
        public bool 置頂YN { get; set; }
        public bool 隱藏YN { get; set; }
        public bool 水桶YN { get; set; }
        public bool 前台刪除YN { get; set; }
        public DateTime 建立日期 { get; set; }
        public DateTime 置頂時間 { get; set; }
        public int 推文數 { get; set; }
        public int 論壇識別 { get; set; }
        public int 回覆狀態 { get; set; }

        public 文章 aobj;

        public 文章回覆() { }
        public 文章回覆(DataRow dr)
        {
            文章流水號 = long.Parse(dr["文章流水號"].ToString());
            回覆流水號 = long.Parse(dr["回覆流水號"].ToString());
            MoloKey = dr["MoloKey"].ToString();
            內容 = dr["內容"].ToString();
            置頂YN = bool.Parse(dr["置頂YN"].ToString());
            隱藏YN = bool.Parse(dr["隱藏YN"].ToString());
            水桶YN = bool.Parse(dr["水桶YN"].ToString());
            前台刪除YN = bool.Parse(dr["前台刪除YN"].ToString());
            置頂時間 = DateTime.Parse(dr["置頂時間"].ToString());
            建立日期 = DateTime.Parse(dr["建立日期"].ToString());
            論壇識別 = int.Parse(dr["論壇識別"].ToString());
            回覆狀態 = int.Parse(dr["回覆狀態"].ToString());
            推文數 = int.Parse(dr["推文數"].ToString());
        }
        public void bindArticle()
        {
            M_Forum MF = new M_Forum();
            DataSet dsself = MF.cureArticle(0,(int)myStatic.siteNow, SortType.日期, SortMethod.遞減, "1", "none", "", 文章流水號);
            aobj = new 文章(dsself.Tables[0].Rows[0]);
        }
    }
}
