//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 新聞點擊
    {
        public int 論壇識別 { get; set; }
        public string 年月日 { get; set; }
        public long 新聞流水號 { get; set; }
        public string 標題 { get; set; }
        public long 點擊率 { get; set; }
        public System.DateTime 更新日期 { get; set; }
    }
}
