//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 新聞
    {
        public int 屬性編號 { get; set; }
        public long 新聞流水號 { get; set; }
        public string 標題 { get; set; }
        public string 內容 { get; set; }
        public int 新聞狀態 { get; set; }
        public bool 置首YN { get; set; }
        public bool 推薦YN { get; set; }
        public string 圖片路徑 { get; set; }
        public string 影片連結 { get; set; }
        public System.DateTime 發佈開始日 { get; set; }
        public Nullable<System.DateTime> 發佈結束日 { get; set; }
        public string 異動者 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public int 論壇識別 { get; set; }
        public long 點擊率 { get; set; }
        public int 相簿編號 { get; set; }
        public string 行動圖片路徑 { get; set; }

        public 新聞()
        {
        }
        public 新聞(DataRow dr)
        {
            屬性編號 = int.Parse(dr["屬性編號"].ToString());
            新聞流水號 = long.Parse(dr["新聞流水號"].ToString());
            標題 = dr["標題"].ToString();
            內容 = dr["內容"].ToString();
            新聞狀態 = int.Parse(dr["新聞狀態"].ToString());
            置首YN = bool.Parse(dr["置首YN"].ToString());
            推薦YN = bool.Parse(dr["推薦YN"].ToString());
            圖片路徑 = dr["圖片路徑"].ToString();
            影片連結 = dr["影片連結"].ToString();
            發佈開始日 = DateTime.Parse(dr["發佈開始日"].ToString());
            if (發佈結束日.HasValue)
             發佈結束日 = DateTime.Parse(dr["發佈結束日"].ToString());
            異動者 = dr["異動者"].ToString();
            建立日期 = DateTime.Parse(dr["建立日期"].ToString());
            論壇識別 = int.Parse(dr["論壇識別"].ToString());
            點擊率 = long.Parse(dr["點擊率"].ToString());
            相簿編號 = int.Parse(dr["相簿編號"].ToString());
            行動圖片路徑 = dr["行動圖片路徑"].ToString();
        }

    }
    
}
