//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 會員計數
    {
        public string MoloKey { get; set; }
        public int 發文次數 { get; set; }
        public int 星海發文次數 { get; set; }
        public int 英雄發文次數 { get; set; }
        public int 英雄攻略次數 { get; set; }
        public int 爐石發文次數 { get; set; }
        public int 回覆次數 { get; set; }
        public int 推文次數 { get; set; }
        public int 留言次數 { get; set; }
        public int 文章總瀏覽數 { get; set; }
        public int 文章被瀏覽數 { get; set; }
        public int FB宣傳次數 { get; set; }
        public int 累計贈送次數 { get; set; }
        public int 登入次數 { get; set; }
        public int 連續登入天數 { get; set; }
        public int 好友數 { get; set; }
        public int 連續簽到天數 { get; set; }
        public int 下載RP次數 { get; set; }
        public int 刪文次數 { get; set; }
        public int 約戰次數 { get; set; }
        public int 被收藏次數 { get; set; }
        public int 總贏次數 { get; set; }
        public int 連贏次數 { get; set; }
        public int 連輸次數 { get; set; }
        public int 下注次數 { get; set; }
    }
}
