//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 會員停權鎖定
    {
        public long 異動編號 { get; set; }
        public int 識別 { get; set; }
        public string MoloKey { get; set; }
        public Nullable<int> 天數 { get; set; }
        public Nullable<System.DateTime> 開始日 { get; set; }
        public Nullable<System.DateTime> 結束日 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public int 論壇識別 { get; set; }
        public bool 永久YN { get; set; }
    }
}
