//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 會員交易
    {
        public long 交易流水號 { get; set; }
        public string 發起方MoloKey { get; set; }
        public string 發起方暱稱 { get; set; }
        public string 接收方MoloKey { get; set; }
        public string 接收方暱稱 { get; set; }
        public int 鐵幣 { get; set; }
        public int 手續費 { get; set; }
        public int 狀態 { get; set; }
        public System.DateTime 建立時間 { get; set; }
        public bool 發起方刪除YN { get; set; }
        public bool 接收方刪除YN { get; set; }
        public int 論壇識別 { get; set; }
    }
}
