//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 會員
    {
        public string MoloKey { get; set; }
        public string Icon名稱 { get; set; }
        public string 暱稱 { get; set; }
        public string 性別 { get; set; }
        public string 生日 { get; set; }
        public string 門號 { get; set; }
        public string 電子信箱 { get; set; }
        public bool 信箱公開YN { get; set; }
        public int 等級 { get; set; }
        public int 經驗值 { get; set; }
        public int 鐵幣 { get; set; }
        public DateTime 上次發文時間;
        public string 上次登入IP { get; set; }
        public DateTime 上次活動時間;
        public int 累計在線時間 { get; set; }
        public DateTime 註冊時間;
        public bool MoloYN { get; set; }
        public int 註冊來源 { get; set; }
        public bool 永久停權YN { get; set; }
        public Nullable<System.DateTime> 停權日期 { get; set; }
        public bool 永久鎖定YN { get; set; }
        public Nullable<System.DateTime> 鎖定日期 { get; set; }
        public DateTime 上次登入時間;
        public string 簽名檔 { get; set; }
        public bool 鐵幣顯示YN { get; set; }
        public string 特殊稱號 { get; set; }
        public string 邊框名稱 { get; set; }
        public string 邊框Icon { get; set; }
        public string 稱號 = "";
        public string myteam = "";
        

        public 會員() { }

        public 會員(DataRow dr)
        {
            MoloKey = dr["MoloKey"].ToString().Trim();
            門號 = dr["門號"].ToString().Trim();
            Icon名稱 = dr["Icon名稱"].ToString().Trim();

            邊框Icon = dr["邊框Icon"].ToString();
            if (邊框Icon == "")
                邊框Icon = "blank.png";
            //if (border != "" && border.IndexOf("http") == -1)
            //    border = myMethod.toClientUrl("~/image/border/" + border);

            暱稱 = dr["暱稱"].ToString().Trim();
            性別 = dr["性別"].ToString().Trim();
            生日 = dr["生日"].ToString().Trim();
            電子信箱 = dr["電子信箱"].ToString().Trim();
            信箱公開YN = bool.Parse(dr["信箱公開YN"].ToString());
            等級 = int.Parse(dr["等級"].ToString());
            經驗值 = int.Parse(dr["經驗值"].ToString());
            鐵幣 = int.Parse(dr["鐵幣"].ToString());
            特殊稱號 = dr["特殊稱號"].ToString();
            稱號 = dr["稱號"].ToString();
            鐵幣顯示YN = bool.Parse(dr["鐵幣顯示YN"].ToString());


            DateTime.TryParse(dr["上次發文時間"].ToString(), out 上次發文時間);
            //if (myStatic.SiteNow != null)
            //    lastLoginTime = UH.GetLastLoginTime(molokey, myStatic.SiteNow.forumIdentity);
            //else
            //    DateTime.TryParse(dr["上次登入時間"].ToString(), out lastLoginTime);
            上次登入IP = dr["上次登入IP"].ToString().Trim();
            DateTime.TryParse(dr["上次活動時間"].ToString(), out 上次活動時間);
            累計在線時間 = int.Parse(dr["累計在線時間"].ToString());

            DateTime.TryParse(dr["註冊時間"].ToString(), out 註冊時間);
            //if (註冊時間 < new DateTime(2014, 4, 28))
            //    isoriginMember = true;

            //if (icon == "")
            //    icon = myMethod.toClientUrl("~/image/content/default.png");
            //else if (icon.IndexOf("http") == -1)
            //    setIcon(icon);//因應舊型的ICON路徑是在本機

            bindSentai();

        }
        //用來呈現的稱號
        public string titleDisplay
        {
            get
            {
                if (特殊稱號 != "")
                    return 特殊稱號;
                else
                    return 稱號;
            }
        }
        #region 戰隊相關

        //綁定自己戰隊成員資訊
        public void bindSentai()
        {
            M_Team MT = new M_Team();
            DataSet ds = MT.DSspfighters(0, 0, 暱稱);
            if (ds.Tables[0].Rows.Count > 0)
                myteam = ds.Tables[0].Rows[0]["戰隊隊名"].ToString();
        }

        #endregion
    }
    
}
