//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 業餘戰隊
    {
        public int 論壇識別 { get; set; }
        public int 戰隊編號 { get; set; }
        public string 戰隊Logo { get; set; }
        public string 戰隊隊名 { get; set; }
        public string 戰隊圖片 { get; set; }
        public string 戰隊簡介 { get; set; }
        public int 成員數 { get; set; }
        public System.DateTime 成立時間 { get; set; }
        public string 備註 { get; set; }
        public bool 關閉YN { get; set; }

        public 業餘戰隊() { }
        public 業餘戰隊(DataRow dr)
        {
            論壇識別 = int.Parse(dr["論壇識別"].ToString());
            戰隊編號 = int.Parse(dr["戰隊編號"].ToString());
            戰隊Logo = dr["戰隊Logo"].ToString();
            戰隊隊名 = dr["戰隊隊名"].ToString();
            戰隊圖片 = dr["戰隊圖片"].ToString();
            戰隊簡介 = dr["戰隊簡介"].ToString();
            成員數 = int.Parse(dr["成員數"].ToString());
            成立時間 = DateTime.Parse(dr["成立時間"].ToString());
            備註 = dr["備註"].ToString();
        }
    }
}
