//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 業餘戰隊約戰
    {
        public long 流水號 { get; set; }
        public int 約戰確認方 { get; set; }
        public int 約戰提出方 { get; set; }
        public System.DateTime 約戰時間 { get; set; }
        public string 約戰原因 { get; set; }
        public string 約戰回覆 { get; set; }
        public int 約戰狀態 { get; set; }
        public System.DateTime 建立日期 { get; set; }
    }
}
