//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 爐石卡片評價
    {
        public string MoloKey { get; set; }
        public long 卡片流水號 { get; set; }
        public int 實用度 { get; set; }
        public int 競技場 { get; set; }
        public System.DateTime 建立日期 { get; set; }
    }
}
