//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 爐石職業
    {
        public long 職業流水號 { get; set; }
        public string 職業名稱 { get; set; }
        public string 職業介紹 { get; set; }
        public string 職業圖片A { get; set; }
        public string 職業圖片B { get; set; }
        public string 職業圖片C { get; set; }
        public string 職業圖片D { get; set; }
        public string 職業圖片E { get; set; }
        public bool 下架YN { get; set; }
    }
}
