//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 爐石卡片
    {
        public long 卡片流水號 { get; set; }
        public string 卡片名稱 { get; set; }
        public string 卡片介紹 { get; set; }
        public int 數量限制 { get; set; }
        public string 一般圖片 { get; set; }
        public string 特殊圖片 { get; set; }
        public string 能力 { get; set; }
        public string 職業 { get; set; }
        public string 類型 { get; set; }
        public string 種族 { get; set; }
        public string 法力 { get; set; }
        public string 攻擊力 { get; set; }
        public string 生命力 { get; set; }
        public string 稀有度 { get; set; }
        public string 系列 { get; set; }
        public string 技能 { get; set; }
        public bool 下架YN { get; set; }
    }
}
