//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 爐石套牌
    {
        public long 套牌流水號 { get; set; }
        public string moLoKey { get; set; }
        public long 卡片流水號 { get; set; }
        public long 攻略流水號 { get; set; }
    }
}
