//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 直播列表
    {
        public int 直播編號 { get; set; }
        public string 行程日期 { get; set; }
        public string 直播名稱 { get; set; }
        public string 直播網址 { get; set; }
        public string 直播狀態 { get; set; }
        public int 人數 { get; set; }
        public Nullable<System.DateTime> 發佈開始日 { get; set; }
        public Nullable<System.DateTime> 發佈結束日 { get; set; }
        public string 異動者 { get; set; }
        public System.DateTime 建立時間 { get; set; }
        public int 論壇識別 { get; set; }
        public string 直播描述 { get; set; }
        public string 直播類別 { get; set; }
    }
}
