//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 稱號設定
    {
        public int 流水號 { get; set; }
        public int 啟始等級 { get; set; }
        public int 結束等級 { get; set; }
        public string 稱號 { get; set; }
    }
}
