//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 英雄聯盟女子比賽_隊員
    {
        public long 隊員編號 { get; set; }
        public long 隊伍編號 { get; set; }
        public string 隊員圖片 { get; set; }
        public int 角色 { get; set; }
        public System.DateTime 修改時間 { get; set; }
        public string 修改者 { get; set; }
    }
}
