//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 英雄攻略
    {
        public long 流水號 { get; set; }
        public long 選手流水號 { get; set; }
        public string 標題 { get; set; }
        public string 英雄介紹 { get; set; }
        public string MoloKey { get; set; }
        public int 人氣數 { get; set; }
        public int 推文數 { get; set; }
        public int 攻略類別 { get; set; }
        public long 英雄流水號 { get; set; }
        public string 符文 { get; set; }
        public string 天賦 { get; set; }
        public string 召喚師 { get; set; }
        public string 道具 { get; set; }
        public string 技能 { get; set; }
        public string 敵對英雄 { get; set; }
        public string 其它道具 { get; set; }
        public string 技能解釋 { get; set; }
        public string 技能解釋Q { get; set; }
        public string 技能解釋W { get; set; }
        public string 技能解釋E { get; set; }
        public string 技能解釋R { get; set; }
        public string 備註 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public bool 置頂YN { get; set; }
        public bool 刪除YN { get; set; }
    }
}
