//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 英雄列表
    {
        public long 流水號 { get; set; }
        public string 英雄名稱 { get; set; }
        public string 被動技 { get; set; }
        public string 被動技Icon { get; set; }
        public string 被動技說明 { get; set; }
        public string 主動技Q { get; set; }
        public string 主動技QIcon { get; set; }
        public string 主動技Q說明 { get; set; }
        public string 主動技W { get; set; }
        public string 主動技WIcon { get; set; }
        public string 主動技W說明 { get; set; }
        public string 主動技E { get; set; }
        public string 主動技EIcon { get; set; }
        public string 主動技E說明 { get; set; }
        public string 主動技R { get; set; }
        public string 主動技RIcon { get; set; }
        public string 主動技R說明 { get; set; }
        public string 圖片路徑 { get; set; }
        public string 背景 { get; set; }
        public System.DateTime 建立日期 { get; set; }
    }
}
