//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂單異動記錄
    {
        public string 訂單編號 { get; set; }
        public int 異動代碼 { get; set; }
        public string 異動名稱 { get; set; }
        public string 異動者 { get; set; }
        public System.DateTime 異動日期 { get; set; }
    }
}
