//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂單遊e金流退款記錄
    {
        public int 流水號 { get; set; }
        public string 訂單編號 { get; set; }
        public decimal 退款金額 { get; set; }
        public int 退款狀態 { get; set; }
        public string 退款方式 { get; set; }
        public string 備註 { get; set; }
        public System.DateTime 時間 { get; set; }
        public int 退款流水號 { get; set; }
    }
}
