//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂單主檔
    {
        public string 訂單編號 { get; set; }
        public string MoloKey { get; set; }
        public int 訂單總額 { get; set; }
        public int 商品狀態 { get; set; }
        public System.DateTime 異動日期 { get; set; }
        public Nullable<System.DateTime> 出貨日期 { get; set; }
        public Nullable<System.DateTime> 預計出貨日期 { get; set; }
        public int 付款方式 { get; set; }
        public string 姓名 { get; set; }
        public System.DateTime 出生日期 { get; set; }
        public string 身份証 { get; set; }
        public string 手機號碼 { get; set; }
        public string 電子信箱 { get; set; }
        public string 出貨地址 { get; set; }
        public string 托運單號 { get; set; }
        public Nullable<byte> 發票格式 { get; set; }
        public Nullable<byte> 載具類別 { get; set; }
        public string 載具顯碼 { get; set; }
        public string 愛心碼 { get; set; }
        public string 公司名稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 公司地址 { get; set; }
        public string 發票號碼 { get; set; }
        public string 備註 { get; set; }
        public System.DateTime 建立日期 { get; set; }
    }
}
