//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂單明細
    {
        public long 流水號 { get; set; }
        public string 訂單編號 { get; set; }
        public long 商品流水號 { get; set; }
        public int 庫存流水號 { get; set; }
        public int 售價 { get; set; }
        public int 鉄幣價格 { get; set; }
        public string 尺寸 { get; set; }
        public string 顏色名稱 { get; set; }
        public int 數量 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public int 退貨數量 { get; set; }
    }
}
