//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 賽事個人報名
    {
        public int 賽事編號 { get; set; }
        public long 流水號 { get; set; }
        public string MoloKey { get; set; }
        public string 姓名 { get; set; }
        public string battleTag { get; set; }
        public string 電子信箱 { get; set; }
        public string 連絡電話 { get; set; }
        public string 身分證 { get; set; }
        public string 帳號 { get; set; }
        public string 職業流水號 { get; set; }
        public string 建議備註 { get; set; }
        public int 論壇識別 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public string ppt帳號 { get; set; }
    }
}
