//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 賽事
    {
        public int 賽事編號 { get; set; }
        public int 論壇識別 { get; set; }
        public string 賽事名稱 { get; set; }
        public string 賽事圖片 { get; set; }
        public string 參賽規則 { get; set; }
        public string 賽事資訊 { get; set; }
        public string 賽程表 { get; set; }
        public string 開始時間 { get; set; }
        public string 結束時間 { get; set; }
        public string 賽事結果 { get; set; }
        public bool 結束YN { get; set; }
        public System.DateTime 建立日期 { get; set; }
    }
}
