//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class 趣味遊戲_對戰表
    {
        public string 遊戲編號 { get; set; }
        public int 場次 { get; set; }
        public string 主隊 { get; set; }
        public int 主隊得分 { get; set; }
        public string 客隊 { get; set; }
        public int 客隊得分 { get; set; }
        public int 論壇識別 { get; set; }
        public string 地圖 { get; set; }
        public string 備註1 { get; set; }
        public string 備註2 { get; set; }
        public System.DateTime 建立日期 { get; set; }
    }
}
