//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    [Serializable]
    public partial class 電競選手
    {
        public long 流水號 { get; set; }
        public string 選手名稱 { get; set; }
        public string 選手圖片 { get; set; }
        public DateTime 年齡;
        public string 國名 { get; set; }
        public DateTime 遊戲年齡;
        public string 競技項目 { get; set; }
        public string 種族 { get; set; }
        public bool 隱藏YN { get; set; }
        public string 使用配備 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public int 論壇識別 { get; set; }
        public string 選手介紹 { get; set; }
        public string 團隊位置 { get; set; }


        public List<擅用英雄> DTexpertin = new List<擅用英雄>();

        public 電競選手(){}
        public 電競選手(DataRow dr)
	    {
            流水號 = long.Parse(dr["流水號"].ToString());
            選手名稱 = dr["選手名稱"].ToString();
            選手圖片 = dr["選手圖片"].ToString();
            DateTime.TryParse(dr["年齡"].ToString(), out 年齡);
            國名 = dr["國名"].ToString();
            DateTime.TryParse(dr["遊戲年齡"].ToString(), out 遊戲年齡);
            競技項目 = dr["競技項目"].ToString();
            種族 = dr["種族"].ToString();
            隱藏YN = bool.Parse(dr["隱藏YN"].ToString());
            使用配備 = dr["使用配備"].ToString();
            建立日期 = DateTime.Parse(dr["建立日期"].ToString());
            論壇識別 = int.Parse(dr["論壇識別"].ToString());
            選手介紹 = dr["選手介紹"].ToString();
            團隊位置 = dr["團隊位置"].ToString();
            //long.TryParse(dr["戰隊編號"].ToString(), out 戰隊編號);
            //sentaiLogo = dr["戰隊Logo"].ToString();
            //teamname = dr["戰隊隊名"].ToString();
            //flag = dr["圖示"].ToString();
	    }

        //綁定擅長角色
        public void BindHero()
        {
            M_Team MT = new M_Team();
            DataSet ds = MT.DSexpertin(流水號);
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                DTexpertin.Add(new 擅用英雄(dr));
            }
        }
        //年齡
        public int age
        {
            get
            {
                return DateTime.Now.Year - 年齡.Year;
            }
        }

        public int gameage
        {
            get
            {
                return DateTime.Now.Year - 遊戲年齡.Year;
            }
        }
    }
}
